import { ResourceIds } from './ResourceIds'

export const commonResourceIds = [
  ResourceIds.SalesInvoice,
  ResourceIds.SalesOrder,
  ResourceIds.CashCountTransaction,
  ResourceIds.CashTransfer,
  ResourceIds.ClientMaster,
  ResourceIds.CreditInvoice,
  ResourceIds.CreditOrder,
  ResourceIds.CashInvoice,
  ResourceIds.InwardSettlement,
  ResourceIds.InwardTransfer,
  ResourceIds.OutwardsModification,
  ResourceIds.OutwardsOrder,
  ResourceIds.OutwardsReturn,
  ResourceIds.ThreeDDesign,
  ResourceIds.Sketch,
  ResourceIds.RemittanceReceiptVoucher,
  ResourceIds.POSPayment,
  ResourceIds.Address,
  ResourceIds.OpenOutwardsReturn,
  ResourceIds.Printing,
  ResourceIds.Worksheet,
  ResourceIds.PaymentOrder,
  ResourceIds.PaymentVouchers,
  ResourceIds.PaymentVoucherExpenses,
  ResourceIds.PaymentOrderExpenses,
  ResourceIds.MaterialsTransfer
]
