export const Buttons = [
    {
        title:'Post',
        condition:'visiblePost',
        onClick:'onPost',
        color:'#231f20',
        disabled:'!editMode',
        image:'post.png',
        main: false,
    },
    {
        title: 'Close',
        color:'transparent',
        image: 'close.png',
        border: '1px solid #01a437',
        main: false,
    },
    {
        title: 'Reopen',
        color:'transparent',
        image: 'reopen.png',
        border: '1px solid #000000',
        main: false,
    },
    {
        title: 'Approval',
        color: '#231f20',
        image: 'approval.png',
        main: false,
    },
    {
        title:'Invoice',
        condition:'onTFR && visibleTFR',
        onClick:'onTFR',
        color:'#231f20',
        disabled:'!isTFR',
        image:'invoice.png',
        main: true,
    },
    {
        title:'Clear',
        condition:'onClear',
        onClick:'onClear',
        color:'#f44336',
        image:'clear.png',
        main: true,
    },
    {
        title:'Client Relation',
        condition:'clientRelation',
        onClick:'onClientRelation',
        color:'#AC48AE',
        disabled:'!editMode',
        image:'clientRelations.png',
        main: true,
    },
    {
        title:'GL',
        condition:'NewComponentVisible',
        onClick:'() => newHandler(recordId)',
        color:'#231f20',
        disabled:'!editMode',
        image:'gl.png',
        main: true,
    },
    {
        title:'Info',
        condition:'onInfo && infoVisible',
        onClick:'onInfo',
        color:'#4355a5',
        disabled:'!editMode',
        image:'info.png',
        main: true,
    },
    {
        title:'Post',
        condition:'onPost && postVisible',
        onClick:'onPost',
        color:'#231f20',
        disabled:'isPosted || !editMode',
        image:'post.png',
        main: true,
    },
    {
        title:'Submit',
        condition:'onSave',
        onClick:'onSave',
        color:'#4eb558',
        disabled:'disabledSubmit || isPosted || isClosed',
        image:'save.png',
        main: true,
    },
    {
        title:'Apply',
        condition:'onApply',
        onClick:'onApply',
        color:'#4eb558',
        disabled:'disabledApply',
        image:'apply.png',
        main: true,
    },
]
