// ** Helpers

const getNewClients= () => {
  return {
    reference: null,
    isResident: false,
    number: null,
    numberEncrypt: null,
    numberVerified: null,
    numberVerifiedEncrypt: null,
    type: null,
    expiryDate: null,
    issusDate: null,
    countryId: null,
    cityId: null,
    idCountry: null,
    idCity: null,
    country: null,
    city: null,
    whatsappNo: null,
    sponsorName: null,
    firstName: null,
    lastName: null,
    middleName: null,
    familyName: null,
    fl_firstName: null,
    fl_lastName: null,
    fl_middleName: null,
    fl_familyName: null,
    birthDate: null,
    nationalityId: null,
    nationality: null,
    profession: null,
    professionId: null,
    cellPhone: null,
    cellPhoneRepeat: null,

    status: null,
    idtId: null,
    oldReference: null,
    salaryRange: null,
    salaryRangeId: null,
    riskLevel: null,
    smsLanguage: null,
    smsLanguageId: null,
    incomeSourceId: null,
    incomeSource: null,
    civilStatus: null,
    civilStatusId: null,
    educationLevel: null,
    educationLevelName: null,
    gender: null,
    genderId: null,
    title: null,
    titleId: null,
    mobileVerified: false,
    otpVerified: false,
    coveredFace: false,
    isEmployee: false,
    isDiplomat: false,
    isRelativeDiplomate: false,
    relativeDiplomateInfo: null,
    name: null,
    countryId: null,
    stateId: null,
    cityId: null,
    cityName: null,
    street1: null,
    street2: null,
    email1: null,
    email2: null,
    phone: null,
    phone2: null,
    phone3: null,
    addressId: null,
    postalCode:null,
    cityDistrictId: null,
    bldgNo: null,
    unitNo: null,
    subNo: null
  }
}

const populateIClients= obj => {
  return {
      reference: obj.reference,
      isResident: obj.isResident,
      number: obj.number,
      numberEncrypt: obj.numberEncrypt,
      numberVerified: obj.numberVerified,
      type: obj.type,
      expiryDate: obj.expiryDate,
      issusDate: obj.issusDate, // address
      countryId: obj.countryId, //address
      cityId: obj.cityId,
      idCountry: obj.idCountry,
      idCity: obj.idCity,
      country: obj.countryName,
      city: obj.city,
      whatsappNo: obj.whatsappNo,
      sponsorName: obj.sponsorName,
      firstName: obj.familyName,
      lastName: obj.lastName,
      middleName: obj.middleName,
      familyName: obj.familyName,
      fl_firstName: obj.fl_firstName,
      fl_lastName: obj.fl_lastName,
      fl_middleName: obj.fl_middleName,
      fl_familyName: obj.fl_familyName,
      birthDate: obj.birthDate,
      nationalityId: obj.nationalityId,
      nationality: obj.nationality,
      profession: obj.profession,
      professionId: obj.professionId,
      cellPhone: obj.cellPhone,
      cellPhoneRepeat: obj.cellPhone,
      status: obj.status,
      idtId: obj.idId,
      oldReference: obj.oldReference,
      salaryRange: obj.salaryRange,
      salaryRangeId: obj.salaryRangeId,
      riskLevel: obj.riskLevel,
      smsLanguage: obj.smsLanguage,
      smsLanguageId: obj.smsLanguageId,
      incomeSourceId: obj.incomeSourceId,
      incomeSource: obj.incomeSource,
      civilStatus: obj.civilStatus,
      civilStatusId: obj.civilStatusId,
      educationLevel: obj.educationLevel,
      educationLevelName: obj.educationLevelName,
      gender: obj.gender,
      genderId: obj.genderId,
      title: obj.title,
      titleId: obj.titleId,
      mobileVerified: obj.mobileVerified,
      otpVerified: obj.otpVerified,
      coveredFace: obj.coveredFace,
      isEmployee: obj.isEmployee,
      isDiplomat: obj.isDiplomat,
      isRelativeDiplomate: obj.isRelativeDiplomate,
      relativeDiplomateInfo: null,
      name: null,
      countryId: null,
      stateId: null,
      cityId: null,   //address
      cityName: null, // address
      street1: null,
      street2: null,
      email1: null,
      email2: null,
      phone: null,
      phone2: null,
      phone3: null,
      addressId: null,
      postalCode:null,
      cityDistrictId: null,
      bldgNo: null,
      unitNo: null,
      subNo: null
  }
}



export { getNewClients, populateIClients }
