import { useContext } from 'react'
import toast from 'react-hot-toast'
import Table from 'src/components/Shared/Table'
import GridToolbar from 'src/components/Shared/GridToolbar'
import { RequestsContext } from 'src/providers/RequestsContext'
import { SystemRepository } from 'src/repositories/SystemRepository'
import { ResourceIds } from 'src/resources/ResourceIds'
import { useResourceQuery } from 'src/hooks/resource'
import { VertLayout } from 'src/components/Shared/Layouts/VertLayout'
import { Fixed } from 'src/components/Shared/Layouts/Fixed'
import { Grow } from 'src/components/Shared/Layouts/Grow'
import { useWindow } from 'src/windows'
import CurrencyForm from './forms/CurrencyForm'
import { ControlContext } from 'src/providers/ControlContext'
import TableNew from 'src/components/Shared/TableNew'

const Currencies = () => {
  const { getRequest, postRequest } = useContext(RequestsContext)
  const { platformLabels } = useContext(ControlContext)

  async function fetchGridData() {
    return await getRequest({
      extension: SystemRepository.Currency.qry,
      parameters: `_filter=`
    })
  }

  const { stack } = useWindow()

  const {
    query: { data },
    labels: _labels,
    refetch,
    invalidate,
    access
  } = useResourceQuery({
    queryFn: fetchGridData,
    endpointId: SystemRepository.Currency.qry,
    datasetId: ResourceIds.Currencies
  })

  const columns = [
    {
      field: 'reference',
      headerName: _labels.reference,
      flex: 1
    },
    {
      field: 'name',
      headerName: _labels.name,
      flex: 1
    },
    {
      field: 'flName',
      headerName: _labels.foreignLanguage,
      flex: 1
    },
    {
      field: 'currencyTypeName',
      headerName: _labels.currencyType,
      flex: 1
    }
  ]

  const del = async obj => {
    try {
      await postRequest({
        extension: SystemRepository.Currency.del,
        record: JSON.stringify(obj)
      })
      invalidate()
      toast.success(platformLabels.Deleted)
    } catch (error) {}
  }

  const add = () => {
    openForm()
  }

  const edit = obj => {
    openForm(obj?.recordId)
  }

  function openForm(recordId) {
    stack({
      Component: CurrencyForm,
      props: {
        labels: _labels,
        recordId: recordId,
        maxAccess: access
      },
      width: 700,
      height: 700,
      title: _labels.currency
    })
  }
  const rowData = [
    {
      currencyTypeName: 'Fiat Money',
      flName: 'درهم اماراتي',
      reference: 'AED',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 4,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'UAE DIRHAMS',
      recordId: 2
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'افغاني',
      reference: 'AFN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 1,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'AFGHANI',
      recordId: 3
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليك ألباني',
      reference: 'ALL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 5,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ALBANIAN LEK',
      recordId: 4
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'AMD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ARMENIAN DRAM',
      recordId: 5
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'غيلدر الأنتيل الهولندية',
      reference: 'ANG',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NETHERLAND ANTILLIAN GUILDER',
      recordId: 6
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'AON',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ANGOLAN NEW KWANZA',
      recordId: 7
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'ARS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 6,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ARGENTINE PESO',
      recordId: 8
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'AUD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 0,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'AUSTRALIAN DOLLAR',
      recordId: 10
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فلورن أروبي',
      reference: 'AWG',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ARUBAN GUILDER',
      recordId: 11
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'AZM',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'AZERBAIJANI MANAT',
      recordId: 12
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'مارك بوسني',
      reference: 'BAM',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NEW DINAR',
      recordId: 13
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار بربادوسي',
      reference: 'BBD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BARBADOS DOLLAR',
      recordId: 14
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'تاكا بنغلاديش',
      reference: 'BDT',
      isoCode: 'BDT',
      symbol: null,
      decimals: 2,
      profileId: 0,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BANGLADESH TAKA',
      recordId: 15
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'BEF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BELGIAN FRANC',
      recordId: 16
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'BGL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BULGARIAN LEV',
      recordId: 17
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار بحريني',
      reference: 'BHD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BAHRAINI DINAR',
      recordId: 18
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك بوروندي',
      reference: 'BIF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BURUNDI FRANC',
      recordId: 19
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار برمودي',
      reference: 'BMD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BERMUDIAN DOLLAR',
      recordId: 20
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار بروناي',
      reference: 'BND',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BRUNEI DOLLAR',
      recordId: 21
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بوليفيانو بوليفي',
      reference: 'BOB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BOLIVIAN BOLIVIANO',
      recordId: 22
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال برازيلي',
      reference: 'BRL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BRAZIL REAL',
      recordId: 23
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار بهامي',
      reference: 'BSD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BAHAMIAN DOLLAR',
      recordId: 24
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'نغولتروم بوتاني',
      reference: 'BTN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BHUTAN NGULTRUM',
      recordId: 25
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بولا بوتسواني',
      reference: 'BWP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BOTSWANA PULA',
      recordId: 26
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'BYB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BELARUSSIAN RUBLE',
      recordId: 27
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار بليزي',
      reference: 'BZD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'BELIZE DOLLAR',
      recordId: 28
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار كتدي',
      reference: 'CAD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CANADIAN DOLLAR',
      recordId: 29
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك سويسري',
      reference: 'CHF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SWISS FRANC',
      recordId: 30
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيزو تشيلي',
      reference: 'CLP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CHILEAN PESO',
      recordId: 31
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'يوان صيني',
      reference: 'CNY',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CHINESE YUAN',
      recordId: 32
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيزو كولومبي',
      reference: 'COP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'COLOMBIAN PESO',
      recordId: 33
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كولون كوستاريكي',
      reference: 'CRC',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'COSTA RICAN COLON',
      recordId: 34
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيزو كوبي',
      reference: 'CUP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CUBAN PESO',
      recordId: 35
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ايسكودو كاب فيردير',
      reference: 'CVE',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CAPE VERDE ESCUDO',
      recordId: 36
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جنيه قبرصي',
      reference: 'CYP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CYPRUS POUND',
      recordId: 37
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كورونا تشيكي',
      reference: 'CZK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CZECH REPUBLIC',
      recordId: 38
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'DEM',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'DEUTSCH MARK',
      recordId: 39
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك جيبوتي',
      reference: 'DJF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'DJIBOUTI FRANC',
      recordId: 40
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كرون دانماركي',
      reference: 'DKK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'DANISH KRONER',
      recordId: 41
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيزو دومنيكاني',
      reference: 'DOP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'DOMINICAN PESO',
      recordId: 42
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار جزائري',
      reference: 'DZD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 6,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ALGERIAN DINAR',
      recordId: 43
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'ECS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ECUADOR SUCRE',
      recordId: 44
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'EEK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ESTONIAN KROON',
      recordId: 45
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جنية مصري',
      reference: 'EGP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'EGYPTIAN POUND',
      recordId: 46
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'ESP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SPAINISH PESTO',
      recordId: 47
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بر اثيوبي',
      reference: 'ETB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ETHOPIAN BIRR',
      recordId: 48
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'يورو',
      reference: 'EUR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 6,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'EURO',
      recordId: 49
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار فيجي',
      reference: 'FJD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'FIJI DOLLAR',
      recordId: 51
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جنيه جزر فوكلاند',
      reference: 'FKP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'FALKLAND ISLANDSPOUND',
      recordId: 52
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'FRF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'FRENCH FRANC',
      recordId: 53
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جنية استرليني',
      reference: 'GBP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GREAT BRITAIN POUND',
      recordId: 54
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'لاري جورجي',
      reference: 'GEL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GEORGIAN LARI',
      recordId: 55
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'سيدي غاني',
      reference: 'GHS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GHANA CEDI',
      recordId: 56
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جنيه جبل طارق',
      reference: 'GIP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GIBRALTAR POUND',
      recordId: 57
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دالاسي غامبيا',
      reference: 'GMD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GAMBIAN DALASI',
      recordId: 58
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك غيني',
      reference: 'GNF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GUINEA FRANC',
      recordId: 59
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'GRD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GREEK DRAKMA',
      recordId: 60
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كتزال غواتيمالي',
      reference: 'GTQ',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GUATEMALA QUETZAL',
      recordId: 61
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'GWP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GUINEA-BISSAU PESO',
      recordId: 62
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار غياني',
      reference: 'GYD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'GUYANA DOLLAR',
      recordId: 63
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار هونج كونج',
      reference: 'HKD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'HONGKONG DOLLAR',
      recordId: 64
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'لمبيرة هندوراسية',
      reference: 'HNL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'HONDURAS LEMPIRA',
      recordId: 65
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كونا كرواتية',
      reference: 'HRK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CROATIA KUNA',
      recordId: 66
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جوردة هايتية',
      reference: 'HTG',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'HAITI GOURDE',
      recordId: 67
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فورنت مجري',
      reference: 'HUF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'HUNGARIAN FORINT',
      recordId: 68
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه اندنوسي',
      reference: 'IDR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'INDONESIAN RUPAIH',
      recordId: 69
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'IEP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'IRISH POUNDS',
      recordId: 70
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'شيكل إسرائيلي',
      reference: 'ILS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ISRAELI SHEKEL',
      recordId: 71
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه هندي',
      reference: 'INR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'INDIAN RUPEES',
      recordId: 72
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار عراقي',
      reference: 'IQD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'IRAQI DINAR',
      recordId: 73
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال ايراني',
      reference: 'IRR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'IRANIAN RIYAL',
      recordId: 74
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كرونة آيسلندية',
      reference: 'ISK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ICELAND KRONA',
      recordId: 75
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'ITL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ITALIAN LIRA',
      recordId: 76
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار جامايكي',
      reference: 'JMD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'JAMAICAN DOLLAR',
      recordId: 77
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار اردني',
      reference: 'JOD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'JORDANIAN DINAR',
      recordId: 78
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ين ياباني',
      reference: 'JPY',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'JAPANESE YEN',
      recordId: 79
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'شلن كيني',
      reference: 'KES',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KENYAN SHILLING',
      recordId: 80
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'سوم قيرغيزستاني',
      reference: 'KGS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KYRGYZSTAN SOM',
      recordId: 81
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال كمبودي',
      reference: 'KHR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CAMBODIAN REIL',
      recordId: 82
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك قمري',
      reference: 'KMF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'COMOROS FRANC',
      recordId: 83
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'وان كوري',
      reference: 'KPW',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NORTH KOREAN WON',
      recordId: 84
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'وون كوري جنوبي',
      reference: 'KRW',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SOUTH KOREAN WON',
      recordId: 85
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار كويتي',
      reference: 'KWD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KUWAITI DINAR',
      recordId: 86
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار جزر كايمان',
      reference: 'KYD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CAYMAN ISLANDS DOLLAR',
      recordId: 87
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'تينغي كازاخستان',
      reference: 'KZT',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KAZAKHSTAN',
      recordId: 88
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كيب لاوي',
      reference: 'LAK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LAOS KIP',
      recordId: 89
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليرة لبناني',
      reference: 'LBP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LEBANESE POUND',
      recordId: 90
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه سيرلانكي',
      reference: 'LKR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SRI LANKAN RUPEES',
      recordId: 91
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار ليبيري',
      reference: 'LRD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LIBERIAN DOLLAR',
      recordId: 92
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'لوتي ليسوتو',
      reference: 'LSL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LESOTHO LOTI',
      recordId: 93
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليتاس ليتواني',
      reference: 'LTL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LITHUANIAN LITAS',
      recordId: 94
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'LUF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LUXEMBOURG FRANCS',
      recordId: 95
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'لاتس لاتفي',
      reference: 'LVL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LATVIAN LAT',
      recordId: 96
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار ليبي',
      reference: 'LYD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LIBYA DINAR',
      recordId: 97
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'درهم مغربي',
      reference: 'MAD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MOROCO DIRHAM',
      recordId: 98
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليو مولدوفي',
      reference: 'MDL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MOLDOVAN LEU',
      recordId: 99
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: ' ',
      reference: 'MGA',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MADAGASCAR ARIARY',
      recordId: 100
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'MGF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MALAGASSY FRANC',
      recordId: 101
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار مقدوني',
      reference: 'MKD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MACEDONIAN DENAR',
      recordId: 102
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'توغروغ منغولي',
      reference: 'MNT',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MONGOLIAN TUGRIK',
      recordId: 103
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'باتاكا ماكاوية',
      reference: 'MOP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MACAU PATACA',
      recordId: 104
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'أوقية موريتانية',
      reference: 'MRU',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MAURITANIAN OUGUIYA',
      recordId: 105
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليرة مالطية',
      reference: 'MTL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MALTESE LIRA',
      recordId: 106
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه موريشي',
      reference: 'MUR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MAURITIAN RUPEE',
      recordId: 107
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روفيا مالديفية',
      reference: 'MVR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MALDIVIAN RUFIYAA',
      recordId: 108
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كواشا ملاوية',
      reference: 'MWK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MALAWIAN KWACHA',
      recordId: 109
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيزو مكسيكي',
      reference: 'MXN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MEXICAN PESO',
      recordId: 110
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'رنجت ماليزي',
      reference: 'MYR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MALAYSIAN RINGIT',
      recordId: 111
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'MZM',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'MOZAMBIQUE METICAL',
      recordId: 112
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار ناميبي',
      reference: 'NAD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NAMIBIA DOLLAR',
      recordId: 113
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'نيرا نيجيري',
      reference: 'NGN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NIGERIA NAIRA',
      recordId: 114
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كوردبا نيكاراغوا',
      reference: 'NIO',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NICARAGUAN CORDOBA ORO',
      recordId: 115
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'NLG',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NETHERLANDS GUILDER',
      recordId: 116
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'NMK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KYAT',
      recordId: 117
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كرون نرويجي',
      reference: 'NOK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NORWAY KRONER',
      recordId: 118
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه نيبالي',
      reference: 'NPR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NEPALESE RUPEES',
      recordId: 119
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار نيوزلاندي',
      reference: 'NZD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'NEWZEALAND DOLLAR',
      recordId: 120
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال عماني',
      reference: 'OMR',
      isoCode: null,
      symbol: null,
      decimals: 3,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'OMANI RIYAL',
      recordId: 121
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بالبوا بنمي',
      reference: 'PAB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PANAMAN BALBOA',
      recordId: 122
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'سول بيروفي جديد',
      reference: 'PEN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PERUVIAN NUEVO SOL',
      recordId: 123
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كينا',
      reference: 'PGK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KINA',
      recordId: 124
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيسو فلبيني',
      reference: 'PHP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PHILIPPINE PESO',
      recordId: 125
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه باكستاني',
      reference: 'PKR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PAKISTANI RUPEES',
      recordId: 126
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'زلوتي بولندي',
      reference: 'PLN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'POLAND ZLOTYCH',
      recordId: 127
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'اسكود برتغالي',
      reference: 'PTE',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PORTUGUESE ESCUDO',
      recordId: 128
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'غواراني باراغواي',
      reference: 'PYG',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PARAGUAY GUARANI',
      recordId: 129
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال قطري',
      reference: 'QAR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'QATARI RIYAL',
      recordId: 130
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليو روماني',
      reference: 'ROL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ROMANIAN LEU',
      recordId: 131
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبل روسي',
      reference: 'RUB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'RUSSIAN ROUBLES',
      recordId: 132
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك رواندي',
      reference: 'RWF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'RWANDA FRANC',
      recordId: 133
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال سعودي',
      reference: 'SAR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SAUDI RIYAL',
      recordId: 134
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار جزر سليمان',
      reference: 'SBD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SOLOMAN ISLANDS DOLLAR',
      recordId: 135
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'روبيه سيشيلي',
      reference: 'SCR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SEYCHELLES RUPEES',
      recordId: 136
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار سوداني',
      reference: 'SDD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SUDANESE DINAR',
      recordId: 137
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كرونه سويدي',
      reference: 'SEK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SWDISH KRONER',
      recordId: 138
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار سنغافوري',
      reference: 'SGD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SINGAPORE DOLLAR',
      recordId: 139
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جنيه سانت هيليني',
      reference: 'SHP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SAINT HELENA POUND',
      recordId: 140
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'تولار سلوفيني',
      reference: 'SIT',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SLOVENIAN TOLAR',
      recordId: 141
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كرونة سلوفاكية',
      reference: 'SKK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SLOVAKI KORUNA',
      recordId: 142
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليون سيراليوني',
      reference: 'SLL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LEONE',
      recordId: 143
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'شلن صومالي',
      reference: 'SOS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SOMALI SHILLING',
      recordId: 144
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'جلدر سورينامي',
      reference: 'SRG',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SURINAME GUILDER',
      recordId: 145
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دوبرا',
      reference: 'STD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'DOBRA',
      recordId: 146
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كولون سلفادوري',
      reference: 'SVC',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'EL SALVADOR COLON',
      recordId: 147
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليرة سوري',
      reference: 'SYP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SYRIAN LERH',
      recordId: 148
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليلانغيني',
      reference: 'SZL',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: 7,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'LILANGEN',
      recordId: 149
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بات تايلاندي',
      reference: 'THB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'THAI BATH',
      recordId: 150
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: null,
      reference: 'TJR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TAJIK ROUBLE',
      recordId: 151
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'منات تركمانستاني',
      reference: 'TMM',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TURKEMENI MANAT',
      recordId: 152
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دينار تونسي',
      reference: 'TND',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TUNISIAN DINAR',
      recordId: 153
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بارانجا',
      reference: 'TOP',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PARANGA',
      recordId: 154
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'اسكود تيموري',
      reference: 'TPE',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TIMOR ESCUDO',
      recordId: 155
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ليرة تركي',
      reference: 'TRY',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TURKISH LIRA',
      recordId: 156
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار ترينيداد وتوباغو',
      reference: 'TTD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TRINIDAD TOBAGO DOLLAR',
      recordId: 157
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار تايوان جديد',
      reference: 'TWD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TIWAN NEW DOLLAR',
      recordId: 158
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'شلن تنزاني',
      reference: 'TZS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TANZANIAN SHILLING',
      recordId: 159
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'هريفنيا اوكراني',
      reference: 'UAH',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'UKRAINIAN HRYVNIA',
      recordId: 160
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'شيلين اوغندي',
      reference: 'UGX',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'UGANDA SHILLING',
      recordId: 161
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار امريكي',
      reference: 'USD',
      isoCode: 'USD',
      symbol: null,
      decimals: 2,
      profileId: 6,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'US DOLLAR',
      recordId: 162
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بيزو أوروغواي',
      reference: 'UYU',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'PESO  URUGUAYO',
      recordId: 163
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'سوم أوزبكستاني',
      reference: 'UZS',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'UZBEKISTAN SUM',
      recordId: 164
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'بوليفار فنزويلي',
      reference: 'VEB',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'VENEZUELAN BOLIVAR',
      recordId: 165
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دونغ فيتنامي',
      reference: 'VND',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'VIETNAM',
      recordId: 166
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فاتو فانواتي',
      reference: 'VUV',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'VATU',
      recordId: 167
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'تالا ساموي',
      reference: 'WST',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'TALA',
      recordId: 168
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'سيفا تشادي',
      reference: 'XAF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CFA FRANC CHADIAN',
      recordId: 169
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار شرق الكاريبي',
      reference: 'XCD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'EAST CARRIBEAN DOLLAR',
      recordId: 170
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'سيفا سنغالي',
      reference: 'XOF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CFA FRANC SENEGALESE',
      recordId: 171
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'فرنك باسيفيكي',
      reference: 'XPF',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'CFP FRANCS',
      recordId: 172
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'ريال يمني',
      reference: 'YER',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'YEMANI RIYAL',
      recordId: 173
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'راند جنوب افريقي',
      reference: 'ZAR',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'SOUTH AFRICAN RAND',
      recordId: 174
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'كواشا زامبي',
      reference: 'ZMK',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'KWACHA',
      recordId: 175
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'زائير',
      reference: 'ZRN',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ZAIRE',
      recordId: 176
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'دولار زيمبابوي',
      reference: 'ZWD',
      isoCode: null,
      symbol: null,
      decimals: 2,
      profileId: null,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: 'ZIMBABWE DOLLAR',
      recordId: 177
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: 'tst',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: 0,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: 'ntst123',
      recordId: 194
    },
    {
      currencyTypeName: 'Metal',
      flName: '',
      reference: 'ttt',
      isoCode: '   ',
      symbol: '',
      decimals: 2,
      profileId: null,
      sale: false,
      purchase: true,
      currencyType: 2,
      name: 'nnn',
      recordId: 195
    },
    {
      currencyTypeName: 'Metal',
      flName: '',
      reference: 'gg',
      isoCode: '   ',
      symbol: '',
      decimals: 2,
      profileId: null,
      sale: false,
      purchase: false,
      currencyType: 2,
      name: 'gggg',
      recordId: 196
    },
    {
      currencyTypeName: 'Metal',
      flName: '',
      reference: 'mmm',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: null,
      sale: false,
      purchase: false,
      currencyType: 2,
      name: 'mmmm',
      recordId: 197
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: 'test',
      reference: 'tes',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: 7,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: 'test',
      recordId: 198
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: '111',
      isoCode: '   ',
      symbol: '',
      decimals: 1,
      profileId: 8,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: '7111268',
      recordId: 199
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: 'fff',
      isoCode: '   ',
      symbol: '',
      decimals: 1,
      profileId: 8,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: 'ffffffffff34',
      recordId: 200
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: '123',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: 8,
      sale: true,
      purchase: true,
      currencyType: 1,
      name: '1233',
      recordId: 204
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: 'sss',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: 0,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: 'sssss',
      recordId: 211
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: 'RRR',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: 1,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: 'testOmar',
      recordId: 212
    },
    {
      currencyTypeName: 'Fiat Money',
      flName: '',
      reference: 'S11',
      isoCode: '   ',
      symbol: '',
      decimals: 0,
      profileId: 0,
      sale: false,
      purchase: false,
      currencyType: 1,
      name: 'S11',
      recordId: 213
    }
  ]
  console.log(data?.list)
  return (
    <VertLayout>
      <Fixed>
        <GridToolbar onAdd={add} maxAccess={access} />
      </Fixed>
      <Grow>
        <Table
          columns={columns}
          gridData={data}
          rowId={['recordId']}
          onEdit={edit}
          onDelete={del}
          refetch={refetch}
          isLoading={false}
          pageSize={50}
          paginationType='client'
          maxAccess={access}
        />
      </Grow>
    </VertLayout>
  )
}

export default Currencies
